### ISSUE TITLE
What data can be accessed?

### ISSUE THREAD

**Issue by abandonedaccount6235** [dyorgio/run-as-root#4]
What kind of data can be accessed from the code run in the other JVM? For example:
```
object ActionRunner {

    fun runActions(computer: String?) {
        val executor = RootExecutor()
        val str = "str"
        executor.run {
            println("Class: " + ActionRunner::class.java.name)
            println("Cool " + str)
        }
    }

}
```
The above is syntactically valid but will it function as expected? is it possible to make it do so? are we limited to the stdlib?

**Comment by dyorgio** [comment]
Hi @Pikachu920, 
I will try to anwser your 3 questions, but please, use stackoverflow to ask things, not github issue system..

1)The above is syntactically valid but will it function as expected? 
Yes.

2) is it possible to make it do so? 
Yes, out-process lib (dep who create new JVM) contains test packages, try out in your machine.

3)are we limited to the stdlib?
No, run-as-root initialize a new JVM with host JVM classpath (original proccess classes, that are not anonymous, will be available).

**Comment by dyorgio** [comment]
@Pikachu920 , I revised your code and I see the problem.
when you use an anounymous class, it will try to serialize parent class too.. like I explained in issue #5 , try to make concrete classes (with constructors to receive your vars) and always keep in mind that serialization is required/envolved.
