### ISSUE TITLE
Filename too long

### ISSUE THREAD

**Issue by neil-benn** [dyorgio/run-as-root#8]
When running this as a simpe test; the code is:
		// Specify JVM options (optional)
		RootExecutor rootExecutor = new RootExecutor("-Xmx64m");

		// Execute privileged action without return
		rootExecutor.run(() -> System.out.println("rmdir \"c:\\Program Files\\test-remove"));

I get an error:

java.io.IOException: Cannot run program ""C:\Users\neilb\AppData\Local\Temp\run-as-root18038586148998856981-elevate"": CreateProcess error=206, The filename or extension is too long

The OS in Win10 64 bit; is there a way to get the filename length down?

**Comment by dyorgio** [comment]
Hi @neil-benn, tks to open this issue ;).
This link: [StackOverflow  Post](https://stackoverflow.com/questions/10519558/createprocess-error-206-the-filename-or-extension-is-too-long-when-running-main) suggests that filename is not the problem, but the classpath.

Take a look in **OutProcessUtils.getCurrentClasspath()** output (call it in your current project main) and verify if is possible to reduce... you can construct your classpath manually too... Copy source of RootExecutor in a new file and replace OneRunOutProcess constructor call with one that accepts custom classpath.

You maybe will like to use  **OutProcessUtils.generateClassPath(Class...)**.

Let me know if you could solve this, I will update library with a new RootExecutor constructor.

**Comment by neil-benn** [comment]
You are correct; this is a spring boot app so there are a _lot_ of jars in the classpath.  It's not so easy to reduce the classpath so something that says 'do not inherit the current classpath would solve the issue.  I was just trawling through your source code for outprocess when I came to the same conclusion :).

**Comment by neil-benn** [comment]
Yep that worked - the actual test doesn't work but the process runs with elevated permissions.  Teh new constructor is:

    /**
     * Creates an instance with specific java options, the classpath can be specified
     * this is useful if you have a lng classpath that breaks commadn line restrictions on Windows
     *
     * @param classPath a custom classpath
     * @param javaOptions JVM options (ex:"-xmx32m")
     */
    public RootExecutor(String classPath, String[] javaOptions) throws IOException {
        this.outProcess = new OneRunOutProcess(MANAGER, classPath, javaOptions);
    }

**Comment by neil-benn** [comment]
However; the fundamental underlying call isn't working too well; I am executing:

		RootExecutor rootExecutor = new RootExecutor(".", new String[] {"-Xmx64m"});
		String command =  "mkdir \"C:\\Program Files\\test-elevate\"";
		System.out.println("executing " + command);
		rootExecutor.run(() -> System.out.println(command));

However; no directory is created.  I've obviously checked this in command prompt and it works (as admin) but not in rootexecutor.  Am I doing something wrong in the command format?

**Comment by neil-benn** [comment]
Nope; no matter what I try the command always returns '1' and fails.  The elevation works perfectly but the command doesn't.

**Comment by dyorgio** [comment]
I see two problems:

1. System.out.println will only print argument on process output, not exec command... It is just an example on README :D. Replace with Runtime.exec.
2. "." as classpath is not sufficient, because at least RootExecutor, OutProcess and deps needs to be on classpath.

Use OutProcessUtils.generateClassPath(RootExecutor.class, OneRunOutProcess.class, YOURCLASSTHATISCREATINGLAMBDAORINNERCLASS.class)

**Comment by neil-benn** [comment]
Thanks; the sysout did seem really weird to me!  I see what you mean about the classpath; in fact because of FST it is massive.  I note that in the source you have got rid of FST.  I think I'll need that version as this makes the dependent libraries much lighter.

**Comment by dyorgio** [comment]
Done! Version 1.2.3 was released.
Please, note that maybe it take some time to you find it on maven respository.

**Comment by dyorgio** [comment]
Closed by timeout.
