### ISSUE TITLE
/tmp/out-process6782787966462853133.dat (Permission denied)

### ISSUE THREAD

**Issue by youndon** [dyorgio/run-as-root#9]
I got this error when i use sample code like:
```
fun main() {
 RootExecutor("-Xmx64m").run{
      println("...")
}
}
```
kotlin 1.40.0
gradle 6.1
OS: Linux Ubuntu 20.4

**Comment by dyorgio** [comment]
Hi @youndon, tks to use this lib :thumbsup:
Issue title suggest that permission of /tmp dir is denied to your no-root user.
So you have 2 options: 
1) Change /tmp permissions to allow no-root users to write on that (maybe it doesn't exists too).
OR
2) Change tmp dir used by your JVM ("~/tmp" maybe...) .

The documentation about it (File.createTempFile) is:

_The default temporary-file directory is specified by the system property java.io.tmpdir. On UNIX systems the default value of this property is typically "/tmp" or "/var/tmp"; on Microsoft Windows systems it is typically "C:\\WINNT\\TEMP". A different value may be given to this system property when the Java virtual machine is invoked, but programmatic changes to this property are not guaranteed to have any effect upon the temporary directory used by this method._

**Comment by youndon** [comment]
Thank you @dyorgio  for respond  this issue, and i tried the options  and yes it was change `tmpdir` option,
So i tried use `export _JAVA_OPTIONS=-Djava.io.tmpdir=/mytmp` command but this always will Picked up because this work only with native code cording to my research so i makes the change in my code and it will be like this:
```
    System.setProperty("java.io.tmpdir", "/mytmp")
    try {
    RootExecutor("-Xmx64m").run {
        println("...")
}
    }catch (ex:Exception){
        println(ex.localizedMessage)
    }
```
the console:
...

**Comment by dyorgio** [comment]
Nice @youndon!
But I will advise you to don't use directories on / (filesystem root).
Use a sub directory on user home (~/).
